export const defaultFocusCompanyOptions = [
  "Adobe",
  "Qualtrics",
  "Domo",
  "BambooHR",
  "Lucid Software",
  "Podium",
  "BILL (Divvy)",
  "Instructure (Canvas)",
  "Ancestry",
  "Pluralsight",
  "Entrata",
  "Weave Communications",
  "eBay",
  "MX Technologies",
  "Health Catalyst",
  "Nearmap",
  "Canopy",
  "ClearLink Technologies",
  "Beyond (Overstock)",
  "Ivanti",
  "MasterControl",
  "HireVue",
  "HealthEquity",
  "Vasion",
  "Solutionreach",
  "Xactware",
  "Galileo Financial",
  "Jane Technologies",
  "Chatbooks"
] as const;
