"use client";

import { useEffect, useMemo, useState } from "react";
import type { CapabilityModelVersion, RecruiterCapabilityModel } from "@/lib/recruiter/types";

const defaultWeights = {
  problem_solving: 30,
  data_communication: 25,
  execution_reliability: 20,
  collaboration: 15,
  business_judgment: 10,
};

const defaultThresholds = {
  emerging_max: 54,
  developing_max: 69,
  ready_max: 84,
};

const defaultEvidence = ["Course performance artifacts", "Applied project outcomes"];

const skeletonBlockClassName = "animate-pulse rounded-lg bg-[#dbe8e2] dark:bg-slate-700/70";

export function RecruiterCapabilityModelsWorkspace() {
  const [models, setModels] = useState<RecruiterCapabilityModel[]>([]);
  const [selectedModelId, setSelectedModelId] = useState<string | null>(null);
  const [selectedModelVersions, setSelectedModelVersions] = useState<CapabilityModelVersion[]>([]);
  const [newModelName, setNewModelName] = useState("Early-Career Data Analyst");
  const [newModelDescription, setNewModelDescription] = useState("Base model for recommendation discovery.");
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [statusMessage, setStatusMessage] = useState<string | null>(null);

  const loadModels = async () => {
    setIsLoading(true);
    try {
      const response = await fetch("/api/recruiter/capability-models", { cache: "no-store" });
      const payload = (await response.json().catch(() => null)) as
        | { ok: true; data: { models: RecruiterCapabilityModel[] } }
        | { ok: false; error?: string }
        | null;

      if (!response.ok || !payload || !payload.ok) {
        throw new Error("capability_models_load_failed");
      }

      setModels(payload.data.models ?? []);
      if ((payload.data.models ?? []).length > 0 && !selectedModelId) {
        setSelectedModelId(payload.data.models[0].capability_model_id);
      }
    } catch {
      setStatusMessage("Unable to load capability models right now.");
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    void loadModels();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    let isActive = true;

    const loadVersions = async () => {
      if (!selectedModelId) {
        setSelectedModelVersions([]);
        return;
      }

      try {
        const response = await fetch(`/api/recruiter/capability-models/${selectedModelId}`, {
          cache: "no-store",
        });
        const payload = (await response.json().catch(() => null)) as
          | {
              ok: true;
              data: {
                model: RecruiterCapabilityModel;
                versions: CapabilityModelVersion[];
              };
            }
          | { ok: false; error?: string }
          | null;

        if (!isActive) return;

        if (!response.ok || !payload || !payload.ok) {
          throw new Error("capability_model_versions_load_failed");
        }

        setSelectedModelVersions(payload.data.versions ?? []);
      } catch {
        if (!isActive) return;
        setSelectedModelVersions([]);
      }
    };

    void loadVersions();

    return () => {
      isActive = false;
    };
  }, [selectedModelId]);

  const selectedModel = useMemo(
    () => models.find((model) => model.capability_model_id === selectedModelId) ?? null,
    [models, selectedModelId]
  );

  const createModel = async () => {
    if (newModelName.trim().length < 2) {
      setStatusMessage("Model name must be at least 2 characters.");
      return;
    }

    setIsSaving(true);
    setStatusMessage(null);

    try {
      const response = await fetch("/api/recruiter/capability-models", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          model_name: newModelName.trim(),
          description: newModelDescription.trim(),
          weights: defaultWeights,
          thresholds: defaultThresholds,
          required_evidence: defaultEvidence,
          notes: "Generated by recruiter workspace v1.",
          publish: false,
        }),
      });

      const payload = (await response.json().catch(() => null)) as
        | { ok: true; data: { model: RecruiterCapabilityModel } }
        | { ok: false; error?: string }
        | null;

      if (!response.ok || !payload || !payload.ok) {
        throw new Error(payload && !payload.ok ? payload.error ?? "capability_model_create_failed" : "capability_model_create_failed");
      }

      setStatusMessage("Created model draft.");
      await loadModels();
      setSelectedModelId(payload.data.model.capability_model_id);
    } catch {
      setStatusMessage("Unable to create capability model.");
    } finally {
      setIsSaving(false);
    }
  };

  const createVersion = async () => {
    if (!selectedModelId) return;

    setIsSaving(true);
    setStatusMessage(null);

    try {
      const response = await fetch(`/api/recruiter/capability-models/${selectedModelId}/versions`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          weights: defaultWeights,
          thresholds: defaultThresholds,
          required_evidence: defaultEvidence,
          notes: "Incremental recalibration from recruiter workspace.",
        }),
      });

      const payload = (await response.json().catch(() => null)) as
        | { ok: true; data: { version: CapabilityModelVersion } }
        | { ok: false; error?: string }
        | null;

      if (!response.ok || !payload || !payload.ok) {
        throw new Error("capability_model_version_create_failed");
      }

      setStatusMessage(`Created version ${payload.data.version.version_number}.`);
      setSelectedModelVersions((current) => [payload.data.version, ...current]);
    } catch {
      setStatusMessage("Unable to create new version.");
    } finally {
      setIsSaving(false);
    }
  };

  const publishVersion = async (version: CapabilityModelVersion) => {
    if (!selectedModelId) return;

    setIsSaving(true);
    setStatusMessage(null);

    try {
      const response = await fetch(
        `/api/recruiter/capability-models/${selectedModelId}/versions/${version.capability_model_version_id}/publish`,
        {
          method: "POST",
        }
      );
      const payload = (await response.json().catch(() => null)) as
        | { ok: true; data: { version: CapabilityModelVersion } }
        | { ok: false; error?: string }
        | null;

      if (!response.ok || !payload || !payload.ok) {
        throw new Error("capability_model_publish_failed");
      }

      setStatusMessage(`Published version ${payload.data.version.version_number}.`);
      setSelectedModelVersions((current) =>
        current.map((item) => {
          if (item.capability_model_version_id === payload.data.version.capability_model_version_id) {
            return payload.data.version;
          }
          if (item.status === "published") {
            return { ...item, status: "archived" };
          }
          return item;
        })
      );
      await loadModels();
    } catch {
      setStatusMessage("Unable to publish selected version.");
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <section className="w-full px-6 py-8 lg:px-8">
      <div className="rounded-[28px] border border-[#cfddd6] bg-[#f8fcfa] p-6 shadow-[0_22px_52px_-34px_rgba(10,31,26,0.45)] dark:border-slate-700 dark:bg-slate-900/75">
        <header className="mb-4">
          <p className="text-xs font-semibold uppercase tracking-[0.12em] text-[#4d675f] dark:text-slate-400">
            Capability Models v1
          </p>
          <h2 className="mt-1 text-2xl font-semibold tracking-tight text-[#0a1f1a] dark:text-slate-100">
            Persisted Models + Immutable Versions
          </h2>
        </header>

        {isLoading ? (
          <div aria-hidden="true" className="space-y-3">
            <div className={`${skeletonBlockClassName} h-16 w-full`} />
            <div className={`${skeletonBlockClassName} h-16 w-full`} />
            <div className={`${skeletonBlockClassName} h-16 w-full`} />
          </div>
        ) : (
          <>
            <div className="grid gap-4 lg:grid-cols-[1.2fr,1fr]">
              <div className="rounded-2xl border border-[#d7e4dd] bg-white p-4 dark:border-slate-700 dark:bg-slate-900/80">
                <h3 className="text-sm font-semibold uppercase tracking-[0.08em] text-[#456158] dark:text-slate-400">
                  Create model draft
                </h3>
                <label className="mt-3 block text-xs font-semibold uppercase tracking-[0.08em] text-[#4c6860] dark:text-slate-400">
                  Model name
                  <input
                    value={newModelName}
                    onChange={(event) => setNewModelName(event.target.value)}
                    className="mt-1 w-full rounded-lg border border-[#bfd2ca] bg-white px-3 py-2 text-sm dark:border-slate-600 dark:bg-slate-900 dark:text-slate-100"
                  />
                </label>

                <label className="mt-2 block text-xs font-semibold uppercase tracking-[0.08em] text-[#4c6860] dark:text-slate-400">
                  Description
                  <textarea
                    value={newModelDescription}
                    onChange={(event) => setNewModelDescription(event.target.value)}
                    rows={3}
                    className="mt-1 w-full rounded-lg border border-[#bfd2ca] bg-white px-3 py-2 text-sm dark:border-slate-600 dark:bg-slate-900 dark:text-slate-100"
                  />
                </label>

                <button
                  type="button"
                  onClick={createModel}
                  disabled={isSaving}
                  className="mt-3 rounded-lg border border-[#b8cdc3] bg-white px-3 py-2 text-sm font-semibold text-[#244a3d] disabled:opacity-70 dark:border-slate-600 dark:bg-slate-900 dark:text-slate-200"
                >
                  {isSaving ? "Saving..." : "Create model"}
                </button>
              </div>

              <div className="rounded-2xl border border-[#d7e4dd] bg-white p-4 dark:border-slate-700 dark:bg-slate-900/80">
                <h3 className="text-sm font-semibold uppercase tracking-[0.08em] text-[#456158] dark:text-slate-400">
                  Existing models
                </h3>
                <div className="mt-3 space-y-2">
                  {models.length === 0 ? (
                    <p className="text-sm text-[#4c6860] dark:text-slate-300">No capability models yet.</p>
                  ) : (
                    models.map((model) => (
                      <button
                        key={model.capability_model_id}
                        type="button"
                        onClick={() => setSelectedModelId(model.capability_model_id)}
                        className={`w-full rounded-lg border px-3 py-2 text-left text-sm ${
                          selectedModelId === model.capability_model_id
                            ? "border-[#3f6d5d] bg-[#eef7f2] dark:border-slate-500 dark:bg-slate-800"
                            : "border-[#d7e4dd] bg-white dark:border-slate-700 dark:bg-slate-900"
                        }`}
                      >
                        <p className="font-semibold text-[#173e33] dark:text-slate-200">{model.model_name}</p>
                        <p className="text-xs text-[#567168] dark:text-slate-400">
                          Active version: {model.active_version_id ?? "none"}
                        </p>
                      </button>
                    ))
                  )}
                </div>
              </div>
            </div>

            <div className="mt-4 rounded-2xl border border-[#d7e4dd] bg-white p-4 dark:border-slate-700 dark:bg-slate-900/80">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <h3 className="text-sm font-semibold uppercase tracking-[0.08em] text-[#456158] dark:text-slate-400">
                  {selectedModel ? `Versions for ${selectedModel.model_name}` : "Model versions"}
                </h3>
                <button
                  type="button"
                  onClick={createVersion}
                  disabled={!selectedModelId || isSaving}
                  className="rounded-lg border border-[#b8cdc3] bg-white px-3 py-2 text-xs font-semibold text-[#244a3d] disabled:opacity-60 dark:border-slate-600 dark:bg-slate-900 dark:text-slate-200"
                >
                  Add version draft
                </button>
              </div>

              <div className="mt-3 space-y-2">
                {selectedModelVersions.length === 0 ? (
                  <p className="text-sm text-[#4c6860] dark:text-slate-300">
                    Select a model to review versions.
                  </p>
                ) : (
                  selectedModelVersions.map((version) => (
                    <article
                      key={version.capability_model_version_id}
                      className="rounded-lg border border-[#d7e4dd] px-3 py-2 dark:border-slate-700"
                    >
                      <div className="flex flex-wrap items-center justify-between gap-2">
                        <p className="text-sm font-semibold text-[#173e33] dark:text-slate-200">
                          v{version.version_number} · {version.status}
                        </p>
                        <button
                          type="button"
                          onClick={() => publishVersion(version)}
                          disabled={isSaving || version.status === "published"}
                          className="rounded-md border border-[#b8cdc3] bg-white px-2 py-1 text-xs font-semibold text-[#244a3d] disabled:opacity-60 dark:border-slate-600 dark:bg-slate-900 dark:text-slate-200"
                        >
                          {version.status === "published" ? "Published" : "Publish"}
                        </button>
                      </div>
                      <p className="mt-1 text-xs text-[#567168] dark:text-slate-400">
                        Created: {new Date(version.created_at).toLocaleString()}
                      </p>
                    </article>
                  ))
                )}
              </div>
            </div>
          </>
        )}

        {statusMessage ? (
          <p className="mt-4 rounded-xl border border-[#cde0d8] bg-[#f4faf7] px-3 py-2 text-xs font-medium text-[#44645b] dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300">
            {statusMessage}
          </p>
        ) : null}
      </div>
    </section>
  );
}
