export const SEED_DEPARTMENTS = [
  { id: 1, name: "Engineering", parent_id: null },
  { id: 2, name: "Product", parent_id: null },
  { id: 3, name: "Design", parent_id: 2 },
  { id: 4, name: "Data Science", parent_id: 1 },
];

export const SEED_JOBS = [
  { id: 1, name: "Software Engineer - Backend", status: "open", department_id: 1 },
  { id: 2, name: "Software Engineer - Frontend", status: "open", department_id: 1 },
  { id: 3, name: "Senior Product Manager", status: "open", department_id: 2 },
  { id: 4, name: "Product Designer", status: "open", department_id: 3 },
  { id: 5, name: "Data Scientist", status: "open", department_id: 4 },
  { id: 6, name: "ML Engineer", status: "closed", department_id: 4 },
  { id: 7, name: "DevOps Engineer", status: "closed", department_id: 1 },
  { id: 8, name: "UX Researcher", status: "draft", department_id: 3 },
];

export const SEED_JOB_STAGES = [
  // Job 1 stages
  { id: 1, job_id: 1, name: "Application Review", order: 1 },
  { id: 2, job_id: 1, name: "Phone Screen", order: 2 },
  { id: 3, job_id: 1, name: "Technical Interview", order: 3 },
  { id: 4, job_id: 1, name: "System Design", order: 4 },
  { id: 5, job_id: 1, name: "Offer", order: 5 },
  // Job 2 stages
  { id: 6, job_id: 2, name: "Application Review", order: 1 },
  { id: 7, job_id: 2, name: "Phone Screen", order: 2 },
  { id: 8, job_id: 2, name: "Frontend Challenge", order: 3 },
  { id: 9, job_id: 2, name: "Final Interview", order: 4 },
  // Job 3 stages
  { id: 10, job_id: 3, name: "Application Review", order: 1 },
  { id: 11, job_id: 3, name: "Hiring Manager Screen", order: 2 },
  { id: 12, job_id: 3, name: "Case Study", order: 3 },
  { id: 13, job_id: 3, name: "Panel Interview", order: 4 },
  { id: 14, job_id: 3, name: "Executive Review", order: 5 },
  { id: 15, job_id: 3, name: "Offer", order: 6 },
  // Job 4 stages
  { id: 16, job_id: 4, name: "Portfolio Review", order: 1 },
  { id: 17, job_id: 4, name: "Design Challenge", order: 2 },
  { id: 18, job_id: 4, name: "Team Interview", order: 3 },
  { id: 19, job_id: 4, name: "Offer", order: 4 },
  // Job 5 stages
  { id: 20, job_id: 5, name: "Application Review", order: 1 },
  { id: 21, job_id: 5, name: "Technical Screen", order: 2 },
  { id: 22, job_id: 5, name: "Take-Home Project", order: 3 },
  { id: 23, job_id: 5, name: "Onsite", order: 4 },
  { id: 24, job_id: 5, name: "Offer", order: 5 },
];

export const SEED_CANDIDATES = [
  { id: 1, first_name: "Alice", last_name: "Chen", email: "alice.chen@example.com", tags: '["new-grad","python"]' },
  { id: 2, first_name: "Bob", last_name: "Martinez", email: "bob.m@example.com", tags: '["experienced","react"]' },
  { id: 3, first_name: "Carol", last_name: "Williams", email: "carol.w@example.com", tags: '["referral"]' },
  { id: 4, first_name: "David", last_name: "Kim", email: "dkim@example.com", tags: '["new-grad"]' },
  { id: 5, first_name: "Eva", last_name: "Johnson", email: "eva.j@example.com", tags: '["experienced","ml"]' },
  { id: 6, first_name: "Frank", last_name: "Davis", email: "frank.d@example.com", tags: '[]' },
  { id: 7, first_name: "Grace", last_name: "Lee", email: "grace.l@example.com", tags: '["referral","senior"]' },
  { id: 8, first_name: "Henry", last_name: "Wilson", email: "henry.w@example.com", tags: '["experienced"]' },
  { id: 9, first_name: "Iris", last_name: "Brown", email: "iris.b@example.com", tags: '["new-grad","design"]' },
  { id: 10, first_name: "James", last_name: "Taylor", email: "j.taylor@example.com", tags: '["senior"]' },
  { id: 11, first_name: "Kate", last_name: "Anderson", email: "kate.a@example.com", tags: '["ml","phd"]' },
  { id: 12, first_name: "Liam", last_name: "Thomas", email: "liam.t@example.com", tags: '[]' },
  { id: 13, first_name: "Mia", last_name: "Jackson", email: "mia.j@example.com", tags: '["referral"]' },
  { id: 14, first_name: "Noah", last_name: "White", email: "noah.w@example.com", tags: '["experienced","backend"]' },
  { id: 15, first_name: "Olivia", last_name: "Harris", email: "olivia.h@example.com", tags: '["new-grad"]' },
  { id: 16, first_name: "Paul", last_name: "Martin", email: "paul.m@example.com", tags: '["senior","fullstack"]' },
  { id: 17, first_name: "Quinn", last_name: "Garcia", email: "quinn.g@example.com", tags: '[]' },
  { id: 18, first_name: "Rachel", last_name: "Martinez", email: "rachel.m@example.com", tags: '["experienced"]' },
  { id: 19, first_name: "Sam", last_name: "Robinson", email: "sam.r@example.com", tags: '["new-grad"]' },
  { id: 20, first_name: "Tina", last_name: "Clark", email: "tina.c@example.com", tags: '["senior","data"]' },
  { id: 21, first_name: "Uma", last_name: "Rodriguez", email: "uma.r@example.com", tags: '["referral","ml"]' },
  { id: 22, first_name: "Victor", last_name: "Lewis", email: "victor.l@example.com", tags: '[]' },
  { id: 23, first_name: "Wendy", last_name: "Lee", email: "wendy.l@example.com", tags: '["design","ux"]' },
  { id: 24, first_name: "Xavier", last_name: "Walker", email: "xavier.w@example.com", tags: '["experienced"]' },
  { id: 25, first_name: "Yara", last_name: "Hall", email: "yara.h@example.com", tags: '["new-grad"]' },
  { id: 26, first_name: "Zach", last_name: "Allen", email: "zach.a@example.com", tags: '["senior","backend"]' },
  { id: 27, first_name: "Amy", last_name: "Young", email: "amy.y@example.com", tags: '["referral"]' },
  { id: 28, first_name: "Brian", last_name: "Hernandez", email: "brian.h@example.com", tags: '[]' },
  { id: 29, first_name: "Cindy", last_name: "King", email: "cindy.k@example.com", tags: '["experienced"]' },
  { id: 30, first_name: "Derek", last_name: "Wright", email: "derek.w@example.com", tags: '["new-grad"]' },
  { id: 31, first_name: "Emma", last_name: "Lopez", email: "emma.l@example.com", tags: '["senior"]' },
  { id: 32, first_name: "Fred", last_name: "Hill", email: "fred.h@example.com", tags: '["referral","backend"]' },
  { id: 33, first_name: "Gina", last_name: "Scott", email: "gina.s@example.com", tags: '[]' },
  { id: 34, first_name: "Hank", last_name: "Green", email: "hank.g@example.com", tags: '["experienced"]' },
  { id: 35, first_name: "Ivy", last_name: "Adams", email: "ivy.a@example.com", tags: '["new-grad","ml"]' },
  { id: 36, first_name: "Jack", last_name: "Baker", email: "jack.b@example.com", tags: '["senior"]' },
  { id: 37, first_name: "Kelly", last_name: "Gonzalez", email: "kelly.g@example.com", tags: '["referral"]' },
  { id: 38, first_name: "Leo", last_name: "Nelson", email: "leo.n@example.com", tags: '[]' },
  { id: 39, first_name: "Maya", last_name: "Carter", email: "maya.c@example.com", tags: '["experienced","design"]' },
  { id: 40, first_name: "Nate", last_name: "Mitchell", email: "nate.m@example.com", tags: '["new-grad"]' },
];

export const SEED_APPLICATIONS = [
  { id: 1, candidate_id: 1, job_id: 1, stage_id: 3, status: "active", applied_at: "2026-01-10T10:00:00Z" },
  { id: 2, candidate_id: 2, job_id: 2, stage_id: 8, status: "active", applied_at: "2026-01-11T09:00:00Z" },
  { id: 3, candidate_id: 3, job_id: 1, stage_id: 2, status: "active", applied_at: "2026-01-12T11:00:00Z" },
  { id: 4, candidate_id: 4, job_id: 3, stage_id: 11, status: "active", applied_at: "2026-01-13T14:00:00Z" },
  { id: 5, candidate_id: 5, job_id: 5, stage_id: 22, status: "active", applied_at: "2026-01-14T08:00:00Z" },
  { id: 6, candidate_id: 6, job_id: 1, stage_id: 1, status: "rejected", applied_at: "2026-01-15T10:00:00Z" },
  { id: 7, candidate_id: 7, job_id: 2, stage_id: 9, status: "active", applied_at: "2026-01-16T13:00:00Z" },
  { id: 8, candidate_id: 8, job_id: 3, stage_id: 13, status: "active", applied_at: "2026-01-17T09:00:00Z" },
  { id: 9, candidate_id: 9, job_id: 4, stage_id: 17, status: "active", applied_at: "2026-01-18T11:00:00Z" },
  { id: 10, candidate_id: 10, job_id: 1, stage_id: 5, status: "active", applied_at: "2026-01-19T10:00:00Z" },
  { id: 11, candidate_id: 11, job_id: 5, stage_id: 23, status: "active", applied_at: "2026-01-20T08:00:00Z" },
  { id: 12, candidate_id: 12, job_id: 2, stage_id: 6, status: "active", applied_at: "2026-01-21T15:00:00Z" },
  { id: 13, candidate_id: 13, job_id: 3, stage_id: 14, status: "active", applied_at: "2026-01-22T10:00:00Z" },
  { id: 14, candidate_id: 14, job_id: 1, stage_id: 4, status: "active", applied_at: "2026-01-23T09:00:00Z" },
  { id: 15, candidate_id: 15, job_id: 4, stage_id: 16, status: "rejected", applied_at: "2026-01-24T11:00:00Z" },
  { id: 16, candidate_id: 16, job_id: 2, stage_id: 7, status: "active", applied_at: "2026-01-25T14:00:00Z" },
  { id: 17, candidate_id: 17, job_id: 5, stage_id: 21, status: "active", applied_at: "2026-01-26T08:00:00Z" },
  { id: 18, candidate_id: 18, job_id: 3, stage_id: 12, status: "active", applied_at: "2026-01-27T10:00:00Z" },
  { id: 19, candidate_id: 19, job_id: 1, stage_id: 2, status: "active", applied_at: "2026-01-28T09:00:00Z" },
  { id: 20, candidate_id: 20, job_id: 5, stage_id: 24, status: "active", applied_at: "2026-01-29T11:00:00Z" },
  { id: 21, candidate_id: 21, job_id: 5, stage_id: 20, status: "active", applied_at: "2026-02-01T10:00:00Z" },
  { id: 22, candidate_id: 22, job_id: 2, stage_id: 8, status: "rejected", applied_at: "2026-02-02T09:00:00Z" },
  { id: 23, candidate_id: 23, job_id: 4, stage_id: 18, status: "active", applied_at: "2026-02-03T11:00:00Z" },
  { id: 24, candidate_id: 24, job_id: 1, stage_id: 3, status: "active", applied_at: "2026-02-04T14:00:00Z" },
  { id: 25, candidate_id: 25, job_id: 3, stage_id: 10, status: "active", applied_at: "2026-02-05T08:00:00Z" },
  { id: 26, candidate_id: 26, job_id: 1, stage_id: 5, status: "hired", applied_at: "2025-12-01T10:00:00Z" },
  { id: 27, candidate_id: 27, job_id: 2, stage_id: 9, status: "hired", applied_at: "2025-12-05T09:00:00Z" },
  { id: 28, candidate_id: 28, job_id: 5, stage_id: 21, status: "active", applied_at: "2026-02-06T10:00:00Z" },
  { id: 29, candidate_id: 29, job_id: 3, stage_id: 15, status: "active", applied_at: "2026-02-07T09:00:00Z" },
  { id: 30, candidate_id: 30, job_id: 4, stage_id: 16, status: "active", applied_at: "2026-02-08T11:00:00Z" },
  { id: 31, candidate_id: 31, job_id: 1, stage_id: 2, status: "active", applied_at: "2026-02-09T14:00:00Z" },
  { id: 32, candidate_id: 32, job_id: 2, stage_id: 7, status: "active", applied_at: "2026-02-10T08:00:00Z" },
  { id: 33, candidate_id: 33, job_id: 5, stage_id: 22, status: "active", applied_at: "2026-02-11T10:00:00Z" },
  { id: 34, candidate_id: 34, job_id: 3, stage_id: 11, status: "active", applied_at: "2026-02-12T09:00:00Z" },
  { id: 35, candidate_id: 35, job_id: 5, stage_id: 23, status: "active", applied_at: "2026-02-13T11:00:00Z" },
  { id: 36, candidate_id: 36, job_id: 1, stage_id: 4, status: "active", applied_at: "2026-02-14T14:00:00Z" },
  { id: 37, candidate_id: 37, job_id: 4, stage_id: 17, status: "active", applied_at: "2026-02-15T08:00:00Z" },
  { id: 38, candidate_id: 38, job_id: 2, stage_id: 6, status: "active", applied_at: "2026-02-16T10:00:00Z" },
  { id: 39, candidate_id: 39, job_id: 4, stage_id: 19, status: "hired", applied_at: "2025-11-15T09:00:00Z" },
  { id: 40, candidate_id: 40, job_id: 3, stage_id: 13, status: "active", applied_at: "2026-02-17T11:00:00Z" },
  // Second applications for some candidates
  { id: 41, candidate_id: 1, job_id: 2, stage_id: 7, status: "active", applied_at: "2026-01-20T10:00:00Z" },
  { id: 42, candidate_id: 5, job_id: 1, stage_id: 2, status: "rejected", applied_at: "2026-01-05T09:00:00Z" },
  { id: 43, candidate_id: 11, job_id: 1, stage_id: 3, status: "active", applied_at: "2026-01-25T11:00:00Z" },
  { id: 44, candidate_id: 20, job_id: 4, stage_id: 18, status: "active", applied_at: "2026-02-01T14:00:00Z" },
  { id: 45, candidate_id: 29, job_id: 1, stage_id: 2, status: "active", applied_at: "2026-02-10T10:00:00Z" },
  { id: 46, candidate_id: 35, job_id: 4, stage_id: 16, status: "active", applied_at: "2026-02-18T09:00:00Z" },
  { id: 47, candidate_id: 7, job_id: 4, stage_id: 17, status: "active", applied_at: "2026-02-19T11:00:00Z" },
  { id: 48, candidate_id: 14, job_id: 5, stage_id: 22, status: "active", applied_at: "2026-02-20T14:00:00Z" },
  { id: 49, candidate_id: 16, job_id: 3, stage_id: 12, status: "active", applied_at: "2026-02-21T08:00:00Z" },
  { id: 50, candidate_id: 18, job_id: 5, stage_id: 20, status: "active", applied_at: "2026-02-22T10:00:00Z" },
  // More spread out
  { id: 51, candidate_id: 2, job_id: 1, stage_id: 3, status: "active", applied_at: "2026-02-23T09:00:00Z" },
  { id: 52, candidate_id: 4, job_id: 2, stage_id: 8, status: "active", applied_at: "2026-02-24T11:00:00Z" },
  { id: 53, candidate_id: 6, job_id: 5, stage_id: 21, status: "active", applied_at: "2026-02-25T14:00:00Z" },
  { id: 54, candidate_id: 8, job_id: 4, stage_id: 16, status: "rejected", applied_at: "2026-02-26T08:00:00Z" },
  { id: 55, candidate_id: 10, job_id: 3, stage_id: 11, status: "active", applied_at: "2026-02-27T10:00:00Z" },
  { id: 56, candidate_id: 12, job_id: 5, stage_id: 22, status: "active", applied_at: "2026-02-28T09:00:00Z" },
  { id: 57, candidate_id: 13, job_id: 1, stage_id: 2, status: "active", applied_at: "2026-03-01T11:00:00Z" },
  { id: 58, candidate_id: 15, job_id: 2, stage_id: 7, status: "active", applied_at: "2026-03-02T14:00:00Z" },
  { id: 59, candidate_id: 17, job_id: 4, stage_id: 18, status: "active", applied_at: "2026-03-03T08:00:00Z" },
  { id: 60, candidate_id: 19, job_id: 5, stage_id: 23, status: "active", applied_at: "2026-03-04T10:00:00Z" },
];

export const SEED_SCORECARDS = [
  { id: 1, application_id: 1, interviewer_name: "Alex Rivera", submitted_at: "2026-01-15T16:00:00Z", recommendation: "strong_yes", attributes: '[{"name":"Problem Solving","rating":"strong_yes"},{"name":"Communication","rating":"yes"},{"name":"Culture Fit","rating":"yes"}]' },
  { id: 2, application_id: 2, interviewer_name: "Jordan Smith", submitted_at: "2026-01-16T15:00:00Z", recommendation: "yes", attributes: '[{"name":"Technical Skills","rating":"yes"},{"name":"Communication","rating":"yes"},{"name":"Initiative","rating":"mixed"}]' },
  { id: 3, application_id: 3, interviewer_name: "Taylor Brown", submitted_at: null, recommendation: null, attributes: '[]' },
  { id: 4, application_id: 5, interviewer_name: "Morgan Davis", submitted_at: "2026-01-20T14:00:00Z", recommendation: "strong_yes", attributes: '[{"name":"ML Knowledge","rating":"strong_yes"},{"name":"Communication","rating":"yes"}]' },
  { id: 5, application_id: 7, interviewer_name: "Casey Wilson", submitted_at: "2026-01-22T15:00:00Z", recommendation: "yes", attributes: '[{"name":"React Skills","rating":"yes"},{"name":"Problem Solving","rating":"yes"}]' },
  { id: 6, application_id: 8, interviewer_name: "Alex Rivera", submitted_at: "2026-01-23T14:00:00Z", recommendation: "mixed", attributes: '[{"name":"Product Thinking","rating":"mixed"},{"name":"Communication","rating":"yes"},{"name":"Leadership","rating":"mixed"}]' },
  { id: 7, application_id: 9, interviewer_name: "Jordan Smith", submitted_at: "2026-01-24T16:00:00Z", recommendation: "yes", attributes: '[{"name":"Design Skills","rating":"yes"},{"name":"Communication","rating":"strong_yes"}]' },
  { id: 8, application_id: 10, interviewer_name: "Taylor Brown", submitted_at: "2026-01-25T15:00:00Z", recommendation: "strong_yes", attributes: '[{"name":"System Design","rating":"strong_yes"},{"name":"Coding","rating":"strong_yes"}]' },
  { id: 9, application_id: 11, interviewer_name: "Morgan Davis", submitted_at: "2026-01-26T14:00:00Z", recommendation: "yes", attributes: '[{"name":"Statistics","rating":"yes"},{"name":"ML Knowledge","rating":"yes"}]' },
  { id: 10, application_id: 13, interviewer_name: "Casey Wilson", submitted_at: "2026-01-28T15:00:00Z", recommendation: "no", attributes: '[{"name":"Product Thinking","rating":"no"},{"name":"Communication","rating":"mixed"}]' },
  { id: 11, application_id: 14, interviewer_name: "Alex Rivera", submitted_at: "2026-01-29T16:00:00Z", recommendation: "yes", attributes: '[{"name":"System Design","rating":"yes"},{"name":"Coding","rating":"yes"}]' },
  { id: 12, application_id: 16, interviewer_name: "Jordan Smith", submitted_at: "2026-02-01T15:00:00Z", recommendation: "mixed", attributes: '[{"name":"React Skills","rating":"mixed"},{"name":"Problem Solving","rating":"yes"}]' },
  { id: 13, application_id: 18, interviewer_name: "Taylor Brown", submitted_at: "2026-02-02T14:00:00Z", recommendation: "strong_yes", attributes: '[{"name":"Product Thinking","rating":"strong_yes"},{"name":"Leadership","rating":"yes"}]' },
  { id: 14, application_id: 20, interviewer_name: "Morgan Davis", submitted_at: "2026-02-04T16:00:00Z", recommendation: "strong_yes", attributes: '[{"name":"Statistics","rating":"strong_yes"},{"name":"ML Knowledge","rating":"strong_yes"}]' },
  { id: 15, application_id: 23, interviewer_name: "Casey Wilson", submitted_at: "2026-02-08T15:00:00Z", recommendation: "yes", attributes: '[{"name":"Design Skills","rating":"yes"},{"name":"UX Thinking","rating":"yes"}]' },
  { id: 16, application_id: 24, interviewer_name: "Alex Rivera", submitted_at: "2026-02-09T14:00:00Z", recommendation: "yes", attributes: '[{"name":"Coding","rating":"yes"},{"name":"Communication","rating":"yes"}]' },
  { id: 17, application_id: 26, interviewer_name: "Jordan Smith", submitted_at: "2025-12-10T15:00:00Z", recommendation: "strong_yes", attributes: '[{"name":"System Design","rating":"strong_yes"},{"name":"Coding","rating":"strong_yes"},{"name":"Culture Fit","rating":"strong_yes"}]' },
  { id: 18, application_id: 27, interviewer_name: "Taylor Brown", submitted_at: "2025-12-15T14:00:00Z", recommendation: "strong_yes", attributes: '[{"name":"React Skills","rating":"strong_yes"},{"name":"Communication","rating":"strong_yes"}]' },
  { id: 19, application_id: 29, interviewer_name: "Morgan Davis", submitted_at: "2026-02-12T16:00:00Z", recommendation: "yes", attributes: '[{"name":"Product Thinking","rating":"yes"},{"name":"Leadership","rating":"strong_yes"}]' },
  { id: 20, application_id: 34, interviewer_name: "Casey Wilson", submitted_at: "2026-02-18T15:00:00Z", recommendation: "mixed", attributes: '[{"name":"Communication","rating":"mixed"},{"name":"Product Thinking","rating":"yes"}]' },
  { id: 21, application_id: 36, interviewer_name: "Alex Rivera", submitted_at: "2026-02-19T14:00:00Z", recommendation: "yes", attributes: '[{"name":"System Design","rating":"yes"},{"name":"Problem Solving","rating":"yes"}]' },
  { id: 22, application_id: 39, interviewer_name: "Jordan Smith", submitted_at: "2025-11-20T15:00:00Z", recommendation: "strong_yes", attributes: '[{"name":"Design Skills","rating":"strong_yes"},{"name":"UX Thinking","rating":"strong_yes"}]' },
  { id: 23, application_id: 40, interviewer_name: "Taylor Brown", submitted_at: "2026-02-22T14:00:00Z", recommendation: "no", attributes: '[{"name":"Product Thinking","rating":"no"},{"name":"Leadership","rating":"mixed"}]' },
  { id: 24, application_id: 41, interviewer_name: "Morgan Davis", submitted_at: "2026-01-25T16:00:00Z", recommendation: "mixed", attributes: '[{"name":"React Skills","rating":"mixed"},{"name":"Communication","rating":"yes"}]' },
  { id: 25, application_id: 43, interviewer_name: "Casey Wilson", submitted_at: "2026-01-30T15:00:00Z", recommendation: "yes", attributes: '[{"name":"Coding","rating":"yes"},{"name":"Problem Solving","rating":"yes"}]' },
  { id: 26, application_id: 48, interviewer_name: "Alex Rivera", submitted_at: "2026-02-25T14:00:00Z", recommendation: "strong_yes", attributes: '[{"name":"ML Knowledge","rating":"strong_yes"},{"name":"Statistics","rating":"yes"}]' },
  { id: 27, application_id: 49, interviewer_name: "Jordan Smith", submitted_at: "2026-02-26T16:00:00Z", recommendation: "yes", attributes: '[{"name":"Product Thinking","rating":"yes"},{"name":"Communication","rating":"yes"}]' },
  { id: 28, application_id: 51, interviewer_name: "Taylor Brown", submitted_at: "2026-02-28T15:00:00Z", recommendation: "mixed", attributes: '[{"name":"Coding","rating":"mixed"},{"name":"System Design","rating":"yes"}]' },
  { id: 29, application_id: 55, interviewer_name: "Morgan Davis", submitted_at: "2026-03-04T14:00:00Z", recommendation: "strong_yes", attributes: '[{"name":"Product Thinking","rating":"strong_yes"},{"name":"Leadership","rating":"yes"}]' },
  { id: 30, application_id: 60, interviewer_name: "Casey Wilson", submitted_at: null, recommendation: null, attributes: '[]' },
];

export const SEED_OFFERS = [
  { id: 1, application_id: 10, status: "extended", created_at: "2026-01-30T10:00:00Z", offer_letter_name: "offer_letter_zach_allen.pdf" },
  { id: 2, application_id: 26, status: "accepted", created_at: "2025-12-15T10:00:00Z", offer_letter_name: "offer_letter_zach_senior.pdf" },
  { id: 3, application_id: 27, status: "accepted", created_at: "2025-12-20T10:00:00Z", offer_letter_name: "offer_letter_grace_lee.pdf" },
  { id: 4, application_id: 29, status: "extended", created_at: "2026-02-12T10:00:00Z", offer_letter_name: "offer_letter_cindy_king.pdf" },
  { id: 5, application_id: 39, status: "accepted", created_at: "2025-11-25T10:00:00Z", offer_letter_name: "offer_letter_maya_carter.pdf" },
  { id: 6, application_id: 11, status: "extended", created_at: "2026-02-01T10:00:00Z", offer_letter_name: "offer_letter_kate_anderson.pdf" },
  { id: 7, application_id: 14, status: "extended", created_at: "2026-02-05T10:00:00Z", offer_letter_name: "offer_letter_noah_white.pdf" },
  { id: 8, application_id: 20, status: "extended", created_at: "2026-02-10T10:00:00Z", offer_letter_name: "offer_letter_tina_clark.pdf" },
  { id: 9, application_id: 43, status: "declined", created_at: "2026-02-05T10:00:00Z", offer_letter_name: null },
  { id: 10, application_id: 36, status: "extended", created_at: "2026-02-20T10:00:00Z", offer_letter_name: "offer_letter_jack_baker.pdf" },
];
